global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9190']
  
  rule_files:
    - "rule/alerts.yml"