global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node_exporter
    static_configs:
      - targets: ['localhost:9190']
  - job_name: "python"
    static_configs:
      - targets: ['localhost:8000']
rule_files:
  - "rule/alerts.yml"
  - "rule/recording_rule.yml"
  
alerting:
  alertmanagers:
    - static_configs:
        - targets: 
          - 'localhost:9093'